// Zed generator — emits one theme-family JSON containing all themes.
// Install: copy to ~/.config/zed/themes/ghostly-rvn.json, then pick it in
// Zed ▸ Settings ▸ Theme.

import { hexa } from "./lib/color.mjs";

const syn = (color, opts = {}) => ({ color, ...opts });

function zedTheme(slug, theme, meta) {
  const s = theme.semantic, sy = theme.syntax, a = theme.ansi;
  const border = s["border.default"];
  const borderV = s["border.muted"];

  const style = {
    border,
    "border.variant": borderV,
    "border.focused": s["accent.primary"],
    "border.selected": s["accent.primary"],
    "border.transparent": hexa(border, 0),
    "border.disabled": borderV,
    "elevated_surface.background": s["bg.surface"],
    "surface.background": s["bg.surface"],
    background: s["bg.base"],
    "element.background": s["bg.surface"],
    "element.hover": s["bg.overlay"],
    "element.active": s["bg.overlay"],
    "element.selected": s["bg.overlay"],
    "element.disabled": s["bg.surface"],
    "drop_target.background": hexa(s["accent.primary"], 0.2),
    "ghost_element.background": hexa(border, 0),
    "ghost_element.hover": s["bg.surface"],
    "ghost_element.active": s["bg.overlay"],
    "ghost_element.selected": s["bg.overlay"],
    text: s["fg.default"],
    "text.muted": s["fg.muted"],
    "text.placeholder": s["fg.faint"],
    "text.disabled": s["fg.faint"],
    "text.accent": s["accent.primary"],
    icon: s["fg.muted"],
    "icon.muted": s["fg.faint"],
    "icon.disabled": s["fg.faint"],
    "icon.placeholder": s["fg.faint"],
    "icon.accent": s["accent.primary"],

    "status_bar.background": s["bg.surface"],
    "title_bar.background": s["bg.surface"],
    "title_bar.inactive_background": s["bg.deep"],
    "toolbar.background": s["bg.base"],
    "tab_bar.background": s["bg.deep"],
    "tab.inactive_background": s["bg.deep"],
    "tab.active_background": s["bg.base"],
    "search.match_background": hexa(s["accent.primary"], 0.25),
    "panel.background": s["bg.deep"],
    "panel.focused_border": s["accent.primary"],
    "pane.focused_border": s["accent.primary"],

    "scrollbar.thumb.background": hexa(s["fg.muted"], 0.25),
    "scrollbar.thumb.hover_background": hexa(s["fg.muted"], 0.4),
    "scrollbar.thumb.border": hexa(border, 0),
    "scrollbar.track.background": hexa(border, 0),
    "scrollbar.track.border": borderV,

    "editor.foreground": s["fg.default"],
    "editor.background": s["bg.base"],
    "editor.gutter.background": s["bg.base"],
    "editor.subheader.background": s["bg.surface"],
    "editor.active_line.background": hexa(s["bg.surface"], 0.6),
    "editor.highlighted_line.background": s["bg.surface"],
    "editor.line_number": s["fg.faint"],
    "editor.active_line_number": s["fg.bright"],
    "editor.invisible": s["fg.faint"],
    "editor.wrap_guide": hexa(border, 0.5),
    "editor.active_wrap_guide": border,
    "editor.document_highlight.read_background": hexa(s["accent.primary"], 0.13),
    "editor.document_highlight.write_background": hexa(s["accent.hot"], 0.13),

    "terminal.background": a.background,
    "terminal.foreground": a.foreground,
    "terminal.bright_foreground": s["fg.bright"],
    "terminal.dim_foreground": s["fg.faint"],
    "terminal.ansi.background": a.background,
    "terminal.ansi.black": a.black,
    "terminal.ansi.red": a.red,
    "terminal.ansi.green": a.green,
    "terminal.ansi.yellow": a.yellow,
    "terminal.ansi.blue": a.blue,
    "terminal.ansi.magenta": a.magenta,
    "terminal.ansi.cyan": a.cyan,
    "terminal.ansi.white": a.white,
    "terminal.ansi.bright_black": a.brightBlack,
    "terminal.ansi.bright_red": a.brightRed,
    "terminal.ansi.bright_green": a.brightGreen,
    "terminal.ansi.bright_yellow": a.brightYellow,
    "terminal.ansi.bright_blue": a.brightBlue,
    "terminal.ansi.bright_magenta": a.brightMagenta,
    "terminal.ansi.bright_cyan": a.brightCyan,
    "terminal.ansi.bright_white": a.brightWhite,

    "link_text.hover": s["accent.primary"],

    conflict: s["signal.warning"],
    "conflict.background": hexa(s["signal.warning"], 0.12),
    "conflict.border": s["signal.warning"],
    created: s["signal.success"],
    "created.background": hexa(s["signal.success"], 0.12),
    "created.border": s["signal.success"],
    deleted: s["signal.danger"],
    "deleted.background": hexa(s["signal.danger"], 0.12),
    "deleted.border": s["signal.danger"],
    error: s["signal.danger"],
    "error.background": hexa(s["signal.danger"], 0.12),
    "error.border": s["signal.danger"],
    hidden: s["fg.faint"],
    hint: s["accent.tertiary"],
    ignored: s["fg.faint"],
    info: s["signal.info"],
    "info.background": hexa(s["signal.info"], 0.12),
    "info.border": s["signal.info"],
    modified: s["accent.secondary"],
    "modified.background": hexa(s["accent.secondary"], 0.12),
    "modified.border": s["accent.secondary"],
    predictive: s["fg.faint"],
    renamed: s["signal.info"],
    success: s["signal.success"],
    unreachable: s["fg.faint"],
    warning: s["signal.warning"],
    "warning.background": hexa(s["signal.warning"], 0.12),
    "warning.border": s["signal.warning"],

    players: [
      { cursor: a.cursor, background: a.cursor, selection: hexa(a.selection, 0.4) },
      { cursor: s["accent.secondary"], background: s["accent.secondary"], selection: hexa(s["accent.secondary"], 0.4) },
      { cursor: s["accent.hot"], background: s["accent.hot"], selection: hexa(s["accent.hot"], 0.4) },
      { cursor: s["signal.success"], background: s["signal.success"], selection: hexa(s["signal.success"], 0.4) },
      { cursor: s["signal.warning"], background: s["signal.warning"], selection: hexa(s["signal.warning"], 0.4) },
      { cursor: s["accent.tertiary"], background: s["accent.tertiary"], selection: hexa(s["accent.tertiary"], 0.4) },
      { cursor: s["signal.danger"], background: s["signal.danger"], selection: hexa(s["signal.danger"], 0.4) },
      { cursor: s["accent.primary"], background: s["accent.primary"], selection: hexa(s["accent.primary"], 0.4) },
    ],

    syntax: {
      attribute: syn(sy.attribute),
      boolean: syn(sy.boolean),
      comment: syn(sy.comment, { font_style: "italic" }),
      "comment.doc": syn(sy.comment, { font_style: "italic" }),
      constant: syn(sy.constant),
      constructor: syn(sy.type),
      embedded: syn(s["fg.default"]),
      emphasis: syn(s["accent.primary"]),
      "emphasis.strong": syn(s["accent.primary"], { font_weight: 700 }),
      enum: syn(sy.type),
      function: syn(sy.function),
      "function.method": syn(sy.method),
      hint: syn(s["accent.tertiary"]),
      keyword: syn(sy.keyword),
      label: syn(sy.tag),
      link_text: syn(s["accent.tertiary"]),
      link_uri: syn(s["accent.primary"], { font_style: "italic" }),
      number: syn(sy.number),
      operator: syn(sy.operator),
      predictive: syn(s["fg.faint"], { font_style: "italic" }),
      preproc: syn(sy.constant),
      primary: syn(s["fg.default"]),
      property: syn(sy.property),
      punctuation: syn(sy.punctuation),
      "punctuation.bracket": syn(sy.punctuation),
      "punctuation.delimiter": syn(sy.punctuation),
      "punctuation.list_marker": syn(sy.tag),
      "punctuation.special": syn(sy["string.escape"]),
      string: syn(sy.string),
      "string.escape": syn(sy["string.escape"]),
      "string.regex": syn(sy.regex),
      "string.special": syn(sy["string.escape"]),
      "string.special.symbol": syn(sy["string.escape"]),
      tag: syn(sy.tag),
      "text.literal": syn(sy.string),
      title: syn(s["fg.bright"], { font_weight: 700 }),
      type: syn(sy.type),
      "type.builtin": syn(sy.type),
      variable: syn(sy.variable),
      "variable.special": syn(sy.parameter),
      variant: syn(sy.constant),
    },
  };

  return {
    name: `${meta.name} ${theme.label}`,
    appearance: theme.appearance,
    style,
  };
}

export default function generate({ meta, themes }) {
  const family = {
    $schema: "https://zed.dev/schema/themes/v0.2.0.json",
    name: meta.name,
    author: meta.author,
    themes: Object.entries(themes).map(([slug, t]) => zedTheme(slug, t, meta)),
  };
  return [{ file: "zed/ghostly-rvn.json", content: JSON.stringify(family, null, 2) + "\n" }];
}
